services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./frontend:/app
      - ./frontend/app/node_modules
    ports:
      - 3000:3000
    networks:
      - giojoe-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /backend/app/node_modules
    ports:
      - 5000:5000
    networks:
      - giojoe-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - giojoe-network

networks:
  giojoe-network:
    driver: bridge
