services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - giojoe-network

networks:
  giojoe-network:
    driver: bridge
